/**:
  ros__parameters:
    minimalist_flocking_translational_velocity: 0.2
    minimalist_flocking_rotational_left_velocity: 2.0
    minimalist_flocking_rotational_right_velocity: -2.0
    minimalist_flocking_drive_timer_period: 0
    minimalist_flocking_zone1_threshold: 0.05
    minimalist_flocking_zone2_threshold: 0.05
    minimalist_flocking_zone3_threshold: 0.08
    minimalist_flocking_zone4_threshold: 0.08
    minimalist_flocking_zone2_robot_threshold: 7
    minimalist_flocking_robot_threshold: 7
    minimalist_flocking_zone_borders: [0.01745329, 2.35619449, 3.92699082, 6.26573201]
    # global params
    max_range: 0.15
    min_range: 0.03
